[shell]
program = "/usr/bin/zsh"

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "Mononoki Nerd Font"
style = "Light"

[font.bold_italic]
family = "Mononoki Nerd Font"
style = "LightItalic"

[font.italic]
family = "Mononoki Nerd Font"
style = "ExtraLightItalic"

[font.normal]
family = "Mononoki Nerd Font"
style = "ExtraLight"


[window]
decorations = "none"
opacity = 0.85

[window.dimensions]
columns = 200
lines = 44
