#!/bin/sh
xrandr --output eDP --primary --mode 1366x768 --pos 1280x453 --rotate normal --output HDMI-A-0 --mode 1280x1024 --pos 0x0 --rotate normal --output DisplayPort-0 --off --output DisplayPort-1 --off
wal -i ~/Images/dragon-girl.jpg > /dev/null
